image: maven:3-eclipse-temurin-21-alpine

stages:
  - build
  - deploy

variables:
  API_DEPLOY_PATH: "/opt/tomcat/webapps/users.war"

before_script:
  - chmod +x ci/setup-mvn-proxy.sh
  - ci/setup-mvn-proxy.sh

  # Sécuriser la clé SSH
  - chmod 400 $CI_SSH_KEY

  # Installer les outils nécessaires
  - apk add --no-cache openssh-client rsync

# Build API-USERS
build_api:
  stage: build
  only:
    - main # Limiter ce job à la branche main
  script:
    # Se placer dans le répertoire tp6 (API)
    - cd ./users
    # Compiler et packager l'API
    - mvn clean package
  artifacts:
    paths:
      - users/target/users.war # Conserver le fichier WAR pour l'étape de déploiement

# Deploy API-USERS
deploy_api:
  stage: deploy
  only:
    - main
  script:
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY users/target/users.war gitlabci@192.168.75.33:$API_DEPLOY_PATH

# Deploy Express Server TEST
deploy_test_express:
  stage: deploy
  only:
    - main
  script:
    - scp -r -o StrictHostKeyChecking=no -i $CI_SSH_KEY ./express/* gitlabci@192.168.75.33:/opt/express
    - ssh -o StrictHostKeyChecking=no -i $CI_SSH_KEY gitlabci@192.168.75.33 "cd /opt/express && pm2 stop server.js && npm install && pm2 restart server.js"

# # Deploy API-GAME
deploy_api_game:
  stage: deploy
  only:
    - main
  before_script:
    - apk add --no-cache openssh-client rsync
    - chmod 400 $CI_SSH_KEY
  script:
    # Copier les fichiers Express vers la VM
    - scp -r -o StrictHostKeyChecking=no -i $CI_SSH_KEY ./api/* gitlabci@192.168.75.33:/opt/api-game

    # Transférer le contenu de la variable .env.production dans un fichier temporaire
    - echo "$ENV_PRODUCTION_API_GAME" > temp.env

    # Copier ce fichier .env.production dans /opt/api-game
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY temp.env gitlabci@192.168.75.33:/opt/api-game/.env.production

    # Lancer / relancer PM2 avec le bon env
    - ssh -o StrictHostKeyChecking=no -i $CI_SSH_KEY gitlabci@192.168.75.33 "
      cd /opt/api-game &&
      pm2 stop server.js || true &&
      npm install &&
      pm2 start server.js --name api-game --env production
      "

# Deploy ADMIN-CLIENT
deploy_api_game:
  stage: deploy
  only:
    - main
  before_script:
    - apk add --no-cache openssh-client rsync
    - chmod 400 $CI_SSH_KEY
  script:
    - cd admim 
    - echo "$ENV_PRODUCTION_ADMIN" > .env.production 
    - npm ci
    - npm run build
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY gitlabci@192.168.75.33:/usr/share/nginx/html/secret/ 

# Deploy front-end
deploy_front:
  stage: deploy
  only:
    - main
  script:
    - scp -r -o StrictHostKeyChecking=no -i $CI_SSH_KEY ./front/index.html gitlabci@192.168.75.33:/usr/share/nginx/html
