image: maven:3-eclipse-temurin-21-alpine

stages:
  - build
  - deploy

variables:
  API_DEPLOY_PATH: "/opt/tomcat/webapps/users.war"

before_script:
  - chmod +x ci/setup-mvn-proxy.sh
  - ci/setup-mvn-proxy.sh

  # Sécuriser la clé SSH
  - chmod 400 $CI_SSH_KEY

  # Installer les outils nécessaires
  - apk add --no-cache openssh-client rsync

# Build API
build_api:
  stage: build
  only:
    - main # Limiter ce job à la branche main
  script:
    # Se placer dans le répertoire tp6 (API)
    - cd ./users
    # Compiler et packager l'API
    - mvn clean package
  artifacts:
    paths:
      - users/target/users.war # Conserver le fichier WAR pour l'étape de déploiement

# Deploy API
deploy_api:
  stage: deploy
  only:
    - main
  script:
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY users/target/users.war gitlabci@192.168.75.33:$API_DEPLOY_PATH
